"""Data processing utilities — intentionally complex for benchmark testing."""

import os


def process_records(records, config):
    """Process a batch of records with validation and transformation.

    This function intentionally has high cyclomatic complexity (CC > 10)
    to exercise the complexity detector.
    """
    results = []
    errors = []

    for record in records:
        if not isinstance(record, dict):
            errors.append(f"Invalid type: {type(record)}")
            continue

        if "id" not in record:
            errors.append("Missing id field")
            continue

        if "type" not in record:
            record["type"] = "default"

        if record["type"] == "user":
            if "email" in record:
                if "@" not in record["email"]:
                    errors.append(f"Invalid email for {record['id']}")
                    continue
                record["email"] = record["email"].lower().strip()
            else:
                errors.append(f"User {record['id']} missing email")
                continue

            if "role" in record:
                if record["role"] not in ("admin", "user", "viewer"):
                    record["role"] = "viewer"
            else:
                record["role"] = "user"

        elif record["type"] == "event":
            if "timestamp" not in record:
                errors.append(f"Event {record['id']} missing timestamp")
                continue

            if "severity" in record:
                if record["severity"] not in ("low", "medium", "high", "critical"):
                    record["severity"] = "low"
            else:
                record["severity"] = "medium"

            if record.get("suppress"):
                continue

        elif record["type"] == "metric":
            if "value" not in record:
                errors.append(f"Metric {record['id']} missing value")
                continue

            try:
                record["value"] = float(record["value"])
            except (ValueError, TypeError):
                errors.append(f"Metric {record['id']} invalid value")
                continue

            if record["value"] < 0:
                record["value"] = 0

        else:
            if config.get("strict_mode"):
                errors.append(f"Unknown type: {record['type']}")
                continue

        if config.get("add_metadata"):
            record["processed"] = True
            record["source"] = config.get("source", "unknown")

        results.append(record)

    return {"results": results, "errors": errors, "total": len(records)}


def long_report_generator(data, options):
    """Generate a report with many sections.

    This function intentionally exceeds the 50-line body threshold
    to exercise the complexity detector's function-length check.
    """
    lines = []
    lines.append("=" * 60)
    lines.append("REPORT")
    lines.append("=" * 60)
    lines.append("")

    # Header section
    lines.append(f"Generated by: {options.get('author', 'system')}")
    lines.append(f"Date: {options.get('date', 'today')}")
    lines.append(f"Format: {options.get('format', 'text')}")
    lines.append("")

    # Summary section
    lines.append("SUMMARY")
    lines.append("-" * 40)
    total = len(data)
    lines.append(f"Total records: {total}")
    lines.append(f"Valid: {sum(1 for d in data if d.get('valid'))}")
    lines.append(f"Invalid: {sum(1 for d in data if not d.get('valid'))}")
    lines.append("")

    # Detail section
    lines.append("DETAILS")
    lines.append("-" * 40)
    for i, item in enumerate(data):
        lines.append(f"  [{i+1}] {item.get('name', 'unnamed')}")
        lines.append(f"      Status: {item.get('status', 'unknown')}")
        lines.append(f"      Value: {item.get('value', 'N/A')}")
    lines.append("")

    # Statistics section
    lines.append("STATISTICS")
    lines.append("-" * 40)
    values = [d.get("value", 0) for d in data if isinstance(d.get("value"), (int, float))]
    if values:
        lines.append(f"  Min: {min(values)}")
        lines.append(f"  Max: {max(values)}")
        lines.append(f"  Sum: {sum(values)}")
        lines.append(f"  Avg: {sum(values) / len(values):.2f}")
    else:
        lines.append("  No numeric values found")
    lines.append("")

    # Categories section
    lines.append("CATEGORIES")
    lines.append("-" * 40)
    categories = {}
    for item in data:
        cat = item.get("category", "uncategorized")
        categories[cat] = categories.get(cat, 0) + 1
    for cat, count in sorted(categories.items()):
        lines.append(f"  {cat}: {count}")
    lines.append("")

    # Footer
    lines.append("=" * 60)
    lines.append("END OF REPORT")
    lines.append("=" * 60)

    return os.linesep.join(lines)
