"""Morning report generator — produces a scannable Markdown report."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path

from sentinel import __version__
from sentinel.models import Finding, RunSummary, Severity


def generate_report(
    findings: list[Finding],
    run: RunSummary,
    output_path: str | Path | None = None,
) -> str:
    """Generate a Markdown morning report from judged, deduped findings.

    Returns the report text. If output_path is provided, also writes to file.
    """
    report = _build_report(findings, run)

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")

    return report


def _build_report(findings: list[Finding], run: RunSummary) -> str:
    """Build the full Markdown report string."""
    lines: list[str] = []

    # Header
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines.append("# Sentinel Morning Report")
    lines.append("")
    lines.append(f"**Repo**: {run.repo_path}")
    lines.append(f"**Scan**: {run.scope.value} | **Generated**: {now}")
    lines.append(f"**Findings**: {len(findings)}")
    lines.append("")

    if not findings:
        lines.append("No issues found. 🎉")
        lines.append("")
        return "\n".join(lines)

    # Summary by severity
    lines.append("## Summary")
    lines.append("")
    severity_counts = _count_by_severity(findings)
    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
        count = severity_counts.get(sev, 0)
        if count > 0:
            lines.append(f"- **{sev.value.upper()}**: {count}")
    lines.append("")

    # New vs recurring breakdown
    recurring_count = sum(
        1 for f in findings
        if f.context and f.context.get("occurrence_count", 1) > 1
    )
    new_count = len(findings) - recurring_count
    lines.append(f"**New**: {new_count} | **Recurring**: {recurring_count}")
    lines.append("")

    # Findings grouped by severity, then category
    grouped = _group_findings(findings)
    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
        if sev not in grouped:
            continue
        lines.append(f"## {sev.value.upper()}")
        lines.append("")

        for category, cat_findings in sorted(grouped[sev].items()):
            lines.append(f"### {category}")
            lines.append("")

            for f in cat_findings:
                lines.append(_format_finding_line(f))
                lines.append("")
                lines.append(_format_evidence_block(f))
                lines.append("")

    # Actions
    lines.append("## Actions")
    lines.append("")
    lines.append("```bash")
    lines.append("sentinel suppress <ID> -r \"reason\"  # Suppress a false positive")
    lines.append("sentinel approve <ID>               # Approve for GitHub issue creation")
    lines.append("sentinel history                     # View past runs")
    lines.append("```")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Report generated by Sentinel v{__version__}*")
    lines.append("")

    return "\n".join(lines)


def _format_finding_line(finding: Finding) -> str:
    """One-line summary of a finding."""
    location = ""
    if finding.file_path:
        location = f"`{finding.file_path}`"
        if finding.line_start:
            location += f":{finding.line_start}"

    confidence_pct = int(finding.confidence * 100)

    badges = ""
    if finding.context:
        occ = finding.context.get("occurrence_count", 1)
        if occ > 1:
            badges += f" ♻️ ×{occ}"
        if finding.context.get("judge_verdict") == "likely_false_positive":
            badges += " ⚠️ FP?"

    # Include fingerprint as ID for suppress/approve commands
    fid = ""
    if finding.fingerprint:
        fid = f" `[{finding.fingerprint}]`"

    return f"- **{finding.title}** — {location} (confidence: {confidence_pct}%){badges}{fid}"


def _format_evidence_block(finding: Finding) -> str:
    """Collapsible evidence block for a finding."""
    lines = ["  <details>", f"  <summary>Evidence ({len(finding.evidence)} items)</summary>", ""]

    for e in finding.evidence:
        lines.append(f"  **{e.type.value}** from `{e.source}`")
        if e.line_range:
            lines.append(f"  Lines {e.line_range[0]}–{e.line_range[1]}")
        lines.append("  ```")
        # Limit evidence content to prevent report bloat
        content = e.content
        content_lines = content.splitlines()
        if len(content_lines) > 20:
            content_lines = [*content_lines[:20], f"  ... ({len(content_lines) - 20} more lines)"]
        # Indent each line of evidence content for proper markdown nesting
        for cline in content_lines:
            lines.append(f"  {cline}")
        lines.append("  ```")
        lines.append("")

    # Add judge summary if available
    if finding.context and "judge" in finding.context:
        judge = finding.context["judge"]
        if "summary" in judge:
            lines.append(f"  **Judge**: {judge['summary']}")
            lines.append("")

    lines.append("  </details>")
    return "\n".join(lines)


def _count_by_severity(findings: list[Finding]) -> dict[Severity, int]:
    counts: dict[Severity, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _group_findings(
    findings: list[Finding],
) -> dict[Severity, dict[str, list[Finding]]]:
    """Group findings by severity, then category."""
    grouped: dict[Severity, dict[str, list[Finding]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for f in findings:
        grouped[f.severity][f.category].append(f)
    return grouped
